const numWords = require("num-words");

exports.createEWayPdf = async (req, res, EwayBill, qrCode) => {
  try {
    const { goods } = EwayBill[1];

    let taxableAmountT = 0;
    let cgstA = 0;
    let sgstA = 0;

    goods.forEach((element) => {
      taxableAmountT += Number(element.taxableAmount?.replace(/\,/g, ""));
      cgstA += Number(element.CGSTAmount);
      sgstA += Number(element.SGSTAmount);
    });

    let totalAmount = taxableAmountT + cgstA + sgstA;

    function EwayBilldateFormate(value) {
      if (value) {
        let date = value.split(" ")[0];
        return date;
      }
      return "";
    }

    function capitalize(word) {
      const lower = word.toLowerCase();
      return word.charAt(0).toUpperCase() + lower.slice(1);
    }

    function convertToWords(value) {
      const rupeesInWords = numWords(value, { and: true });
      return rupeesInWords.charAt(0).toUpperCase() + rupeesInWords.slice(1); // Capitalize the first letter
    }

    const textCapitalize = (value) => {
      if (value) {
        const words = value.split(" ");

        for (let i = 0; i < words.length; i++) {
          words[i] = words[i][0].toUpperCase() + words[i].substr(1);
        }
        return words.join(" ");
      } else {
        return "";
      }
    };

    const signText = (value) => {
      if (value) {
        const words = value.split("@");
        return words[0];
      } else {
        return "";
      }
    };

    const documentDefinition = {
      info: {
        title: "e-Way Bill",
      },
      content: [
        {
          text: `e-Way Bill`,
          style: "coloredText",
          fontSize: 18,
          bold: true,
          alignment: "center",
          margin: [0, 0, 0, 10],
          border: [false, false, false, false],
        },
        {
          margin: [0, 10, 0, 0],
          table: {
            headerRows: 1,
            widths: ["*", "*"],
            body: [
              [
                {
                  text: `Delivery challan number : ${
                    EwayBill[0].docNo ? EwayBill[0].docNo : ""
                  }`,
                  bold: true,
                  fontSize: 12,
                  border: [false, false, false, false],
                },
                {
                  image: qrCode,
                  width: 100,
                  height: 100,
                  alignment: "right",
                  margin: [0, 0, 0, 10],
                  border: [false, false, false, false],
                },
              ],
              [
                {
                  text: `Delivery challan date: ${EwayBilldateFormate(
                    EwayBill && EwayBill[0] ? EwayBill[0].ewayBillDate : "-"
                  )}`,
                  bold: true,
                  fontSize: 12,

                  border: [false, false, false, false],
                },
                {
                  text: "",
                  border: [false, false, false, false],
                  bold: true,
                },
              ],
            ],
          },
        },
        {
          margin: [0, 10, 0, 0],
          table: {
            headerRows: 1,
            widths: ["*"],
            body: [
              [
                {
                  text: "1. e-Way Bill Details",
                  fontSize: 12,
                  bold: true,
                  border: [1, 1, 1, 1],
                },
              ],
            ],
          },
        },
        {
          margin: [0, 10, 0, 10],
          table: {
            headerRows: 1,
            widths: ["*", "*", "*"],
            body: [
              [
                {
                  text: `e-Way Bill No. : ${EwayBill[0]?.ewbNo}`,
                  fontSize: 10,
                  bold: false,
                },
                {
                  text: `Mode : ${capitalize(EwayBill[1]?.transportmode)}`,
                  fontSize: 10,
                  bold: false,
                },
                {
                  text: `Generated Date : ${
                    EwayBill &&
                    EwayBill[0] &&
                    EwayBill[0].ewayBillDate &&
                    EwayBill[0].ewayBillDate.split(" ") &&
                    EwayBill[0].ewayBillDate.split(" ")[0]
                  }`,
                  fontSize: 10,
                  bold: false,
                },
              ],
              [
                {
                  text: `Generated By:${textCapitalize(
                    signText(EwayBill[1].initialgeneratedby)
                  )}`,
                  fontSize: 10,
                  bold: false,
                },
                {
                  text: `Approx Distance : ${EwayBill[1].approxDistance} KM`,
                  fontSize: 10,
                  bold: false,
                },
                {
                  text: `Valid Upto : ${
                    EwayBill &&
                    EwayBill[0] &&
                    EwayBill[0].validUpto &&
                    EwayBill[0].validUpto.split(" ") &&
                    EwayBill[0].validUpto.split(" ")[0]
                  }`,
                  fontSize: 10,
                  bold: false,
                },
              ],
              [
                {
                  text: "Supply Type: Others",
                  fontSize: 10,
                  bold: false,
                },
                {
                  text: "Transction Type: Regular",
                  fontSize: 10,
                  bold: false,
                },
                {
                  text: "Supply Reason: Transport of goods under lease",
                  fontSize: 10,
                  bold: false,
                },
              ],
            ],
          },
        },
        {
          margin: [0, 10, 0, 0],
          table: {
            headerRows: 1,
            widths: ["*"],
            body: [
              [
                {
                  text: "2. Address Details",
                  fontSize: 12,
                  bold: true,
                },
              ],
            ],
          },
        },
        {
          margin: [0, 10, 0, 10],
          table: {
            headerRows: 1,
            widths: ["*", "*"],
            body: [
              [
                {
                  text: "From",
                  fontSize: 10,
                  bold: true,
                },
                {
                  text: "To",
                  fontSize: 10,
                  bold: true,
                },
              ],
              [
                {
                  text: `${textCapitalize(EwayBill[1]?.shippingCustAdd)}`,
                  fontSize: 10,
                  bold: false,
                },
                {
                  text: `${textCapitalize(EwayBill[1].address)}`,
                  fontSize: 10,
                  bold: false,
                },
              ],
              [
                {
                  text: `GSTIN: ${textCapitalize(EwayBill[1]?.gstin)}`,
                  fontSize: 10,
                  bold: false,
                },
                {
                  text: `GSTIN: ${textCapitalize(EwayBill[1]?.gstin)}`,
                  fontSize: 10,
                  bold: false,
                },
              ],
              [
                {
                  text: "Gujarat",
                  fontSize: 10,
                  bold: false,
                },
                {
                  text: `${textCapitalize(EwayBill[1]?.placeofsupply)}`,
                  fontSize: 10,
                  bold: false,
                },
              ],
              [
                {
                  text: "Dispatch From",
                  fontSize: 10,
                  bold: true,
                },
                {
                  text: "Ship To",
                  fontSize: 10,
                  bold: true,
                },
              ],
              [
                {
                  text: `${textCapitalize(EwayBill[1]?.placeofsupply)}`,
                  fontSize: 10,
                  bold: false,
                },
                {
                  text: `${textCapitalize(EwayBill[1]?.address)}`,
                  fontSize: 10,
                  bold: false,
                },
              ],
            ],
          },
        },
        {
          margin: [0, 10, 0, 0],
          table: {
            headerRows: 1,
            widths: ["*"],
            body: [
              [
                {
                  text: "3. Goods Details",
                  fontSize: 12,
                  bold: true,
                },
              ],
            ],
          },
        },
        {
          margin: [0, 20, 0, 0],
          widths: ["*", "*", "*", "*", "*"],
          fontSize: 10,
          table: {
            body: [
              [
                "HSN code",
                "Product Name & Desc",
                "Quantity",
                "Taxable Amount",
                "Rate (CGST)",
                "Amount (CGST)",
                "Rate (SGST)",
                "Amount (SGST)",
              ],
              ...goods.map((item) => [
                {
                  text: item.hsn,
                },
                {
                  text: `${item.materialDescriptionHOCCO}\n${item.materialDescriptionVendor}`,
                },
                {
                  text: "1",
                },
                {
                  text: item.taxableAmount,
                },
                {
                  text: item.CGSTRate,
                },
                {
                  text:
                    item.CGSTAmount?.toFixed(2) % 1 > 0.5
                      ? Math.ceil(item.CGSTAmount)
                      : Math.floor(item.CGSTAmount),
                },
                {
                  text: item.SGSTRate,
                },
                {
                  text:
                    item.SGSTAmount?.toFixed(2) % 1 > 0.5
                      ? Math.ceil(item.SGSTAmount)
                      : Math.floor(item.SGSTAmount),
                },
              ]),
            ],
          },
        },
        {
          margin: [0, 10, 0, 0],
          table: {
            headerRows: 1,
            widths: ["*", "*"],
            body: [
              [
                {
                  text: `Total challan amount in Rs.: ${
                    totalAmount.toFixed(2) % 1 > 0.5
                      ? Math.ceil(totalAmount)
                      : Math.floor(totalAmount)
                  }`,
                  fontSize: 12,
                  border: [true, true, false, true],
                  bold: true,
                },
                {
                  text: `Total challan amount in words: ${textCapitalize(
                    convertToWords(
                      totalAmount.toFixed(2) % 1 > 0.5
                        ? Math.ceil(totalAmount)
                        : Math.floor(totalAmount)
                    )
                  )}`,
                  fontSize: 12,
                  border: [true, true, true, true],
                  bold: true,
                },
              ],
            ],
          },
        },
        {
          margin: [0, 10, 0, 0],
          table: {
            headerRows: 1,
            widths: ["*"],
            body: [
              [
                {
                  text: "4. Transportation Details",
                  fontSize: 12,
                  bold: true,
                },
              ],
            ],
          },
        },
        {
          margin: [0, 10, 0, 10],
          table: {
            headerRows: 1,
            widths: ["*"],
            body: [
              [
                {
                  text: `Transporter ID :${
                    EwayBill[1]?.transporternametype === "C"
                      ? textCapitalize(EwayBill[1]?.transportername)
                      : ""
                  }`,
                  fontSize: 10,
                  bold: true,
                },
              ],
              [
                {
                  text: `Name : ${
                    EwayBill[1]?.transporternametype === "P"
                      ? textCapitalize(EwayBill[1]?.transportername)
                      : ""
                  }`,
                  fontSize: 10,
                  bold: true,
                },
              ],
            ],
          },
        },
        {
          margin: [0, 10, 0, 0],
          table: {
            headerRows: 1,
            widths: ["*"],
            body: [
              [
                {
                  text: "5. Vehicle Details",
                  fontSize: 12,
                  bold: true,
                },
              ],
            ],
          },
        },
        {
          margin: [0, 10, 0, 10],
          table: {
            headerRows: 1,
            widths: ["*", "*", "*"],
            body: [
              [
                {
                  text: `Vehicle No : ${textCapitalize(
                    EwayBill[1]?.vehiclenumber
                  )}`,
                  fontSize: 10,
                  bold: true,
                },
                {
                  text: `From : ${textCapitalize(EwayBill[1]?.placeofsupply)}`,
                  fontSize: 10,
                  bold: true,
                },
                {
                  text: "CEWB No : ",
                  fontSize: 10,
                  bold: true,
                },
              ],
            ],
          },
        },
      ],
      // footer: function (currentPage, pageCount) {
      //   return {
      //     columns: [
      //       {
      //         text: `Page ${currentPage} of ${pageCount}`,
      //         alignment: "right",
      //         margin: [0, 0, 20, 0],
      //       },
      //     ],
      //   };
      // },
    };

    return documentDefinition;
  } catch (error) {
    if (!res.headersSent) {
      res.status(500).send("Internal Server Error");
    }
  }
};
