const mongoose = require('mongoose');

const dfformSchema = mongoose.Schema({
    userId: {
        type: String,
    },
    equipmentAutoGenerated: {
        type: String,
    },
    assetSerialNumber: {
        type: String,
    },
    assetStatus: {
        type: String,
    },
    materialHOCCO: {
        type: String,
    },
    materialDescriptionHOCCO: {
        type: String,
    },
    manufacture: {
        type: String,
    },
    constructionDateInvoiceDate: {
        type: String,
    },
    materialVendor: {
        type: String,
    },
    materialDescriptionVendor: {
        type: String,
    },
    custCode: {
        type: String,
    },
    custName: {
        type: String,
    },
    custType: {
        type: String,
    },
    installationDate: {
        type: String,
    },
    uninstallationDate: {
        type: String,
    },
    DFType: {
        type: String,
    },
    paymentMode: {
        type: String,
    },
    chequeBankInCaseOfChequePay: {
        type: String,
    },
    chequeDateInCaseOfChequePay: {
        type: String,
    },
    chequeNumberInCaseOfChequePay: {
        type: String,
    },
    payment_ClearaceDate: {
        type: String,
    },
    paymentRefNoInCaseOfOnlinePay: {
        type: String,
    },
    depositAmount: {
        type: String,
    },
    purchaseValueHOCCO: {
        type: String,
    },
    bookValue: {
        type: String,
    },
    returnPaymentDate: {
        type: String,
    },
    returnPaymentAmount: {
        type: String,
    },
    refundChequeDate: {
        type: String,
    },
    refundChequeNo: {
        type: String,
    },
    rentStartDate: {
        type: String,
    },
    lastScanDate: {
        type: String,
    },
    scanBy: {
        type: String,
    },
    assetStatus: {
        type: String,
    },
    vendorWarrantyStart: {
        type: String,
    },
    vendorWarrantyEnd: {
        type: String,
    },
},
{ timestamps: true }
);

module.exports = mongoose.model('dfform', dfformSchema);