const mongoose = require("mongoose");

const dfMasterSchema = mongoose.Schema(
  {
    equipmentAutoGenerated: {
      type: String,
    },
    assetSerialNumber: {
      type: String,
    },
    barCode: {
      type: String,
    },
    materialCodeHOCCO: {
      type: String,
    },
    materialDescriptionHOCCO: {
      type: String,
    },
    manufacture: {
      type: String,
    },
    constructionDateInvoiceDate: {
      type: String,
    },
    materialVendor: {
      type: String,
    },
    materialDescriptionVendor: {
      type: String,
    },
    custCode: {
      type: String,
    },
    custName: {
      type: String,
    },
    custType: {
      type: String,
    },
    installationDate: {
      type: String,
    },
    uninstallationDate: {
      type: String,
    },
    dfType: {
      type: String,
    },
    paymentMode: {
      type: String,
    },
    chequeBankInCaseOfChequePay: {
      type: String,
    },
    chequeDateInCaseOfChequePay: {
      type: String,
    },
    chequeNumberInCaseOfChequePay: {
      type: String,
    },
    paymentClearaceDate: {
      type: String,
    },
    paymentRefNoInCaseOfOnlinePay: {
      type: String,
    },
    depositAmount: {
      type: Number,
    },
    purchaseValueHOCCO: {
      type: String,
    },
    bookValue: {
      type: String,
    },
    returnPaymentDate: {
      type: String,
    },
    returnPaymentAmount: {
      type: String,
    },
    refundChequeDate: {
      type: String,
    },
    refundChequeNo: {
      type: String,
    },
    rentStartDate: {
      type: String,
    },
    lastScanDate: {
      type: String,
    },
    scanBy: {
      type: String,
    },
    assetStatus: {
      type: String,
    },
    vendorWarrantyStart: {
      type: String,
    },
    vendorWarrantyEnd: {
      type: String,
    },
    currentCustId: {
      type: String,
    },
    trackingStatus: {
      type: String,
      enum: ["Tag", "Agreement", "Release"],
      default: "Tag",
    },
    shortFiled: {
      type: String,
    },
    dfCategory: {
      type: String,
    },
    stateName: {
      type: String,
    },
    poDetails: {
      type: String,
    },
    poNumber: {
      type: String,
    },
    poDate: {
      type: String,
    },
    invoiceNumber: {
      type: String,
    },
    invoiceDate: {
      type: String,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("dfMaster", dfMasterSchema);
